<a href="https://colab.research.google.com/github/devpandey01/Introduction-to-Dl-AI/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Adding vectors in Python

In [2]:
x = [1,2,3]
y = [4,5,6]

z = []
for i in range(len(x)):
  z.append(x[i]+y[i])
print(z)

[5, 7, 9]


# Adding vectors using NumPy Array

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = x + y
z

array([5, 7, 9])

# List vs NumPy



In [13]:
x = list(range(1,100001))

4.43 ms ± 392 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
%timeit [2 * i for i in x]
%timeit 2 * y

4.34 ms ± 118 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
71.2 µs ± 12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


**`range`** vs **`arange`**

In [7]:
for i in range(1,5):
  print(i)

1
2
3
4


In [5]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

# **Element-Wise Multiplication** (Hadamard Product)

In [8]:
a = np.arange(1,4)
b = np.arange(4,7)
z = a * b
z

array([ 4, 10, 18])

**Scaling Vectors**

In [9]:
x = np.arange(1,4)
y = 3 * x
y

array([3, 6, 9])

*Squaring of Numbers*

In [16]:
x = np.arange(1,100001)
y = x ** 2

In [ ]:
x = np.arange(1,100001)
y = np.log10(x) # base 10
y = np.log(x) #base e

Adding Constant to a Vector

In [17]:
x = np.arange(1,4)
c = 5
y = x + c
y

array([6, 7, 8])

# *Write Functions*

example `f(x) = 5x-2`

In [18]:
x = np.arange(1,4)
y = 5*x - 2
y

array([ 3,  8, 13])

## Dot Product

In [25]:
x = np.arange(1,5)
y = np.arange(-4,-8,-1)

z = np.dot(x,y) # or we can use x @ y

*Vectors of Zeros or Ones and Transpose Vectors*

In [29]:
zeros = np.zeros(5)
ones = np.ones(5)

fives = 5*ones

fives.T

array([5., 5., 5., 5., 5.])

# Norm of a Vector
 x = [1, 2, 3]

 L1 norm = ||x|| = |1| + |2| + |3| = 6

 L2 norm = ||x|| =  |1| + |2| + |3| = 3.74


In [32]:
x = np.array([1,2,3])
y = np.linalg.norm(x) # L2 norm
z = np.linalg.norm(x, ord = 1) #L1 norm
print(y,z)

3.7416573867739413 6.0


# Shape And Dimensions In Vectors

In [46]:
x = np.array([1,2,3,4])
x.shape

(4,)

In [47]:
x.ndim

1